### ISSUE TITLE
Does not log in to TickTick

### ISSUE THREAD

**Issue by kmaustral** [viduycheung/ticktick-obsidian#1] opened 2023-09-11 21:23 UTC
It's great to see this plug-in. I'm excited to try it out. 

When I go to login to TickTick from the settings, I get a dialogue asking me to allow TickTick for Obsidian to access my TickTick account. I click Allow, but then the window goes blank. None of the commands will work.

**Comment by viduycheung** [comment] 2023-09-12 01:15
Sorry about that. Unfortunately, I can't reproduce your issue. Please try again record a video about the login process and provide your system info to help me figure out this issue.

**Comment by kmaustral** [comment] 2023-09-12 02:35
Here's a recording: https://www.loom.com/share/159dfa4b07ad4ef7bc391f7b9e9c37f3?sid=d451db68-1d9d-424b-9f15-2bdcc92acb06
I'm on the latest Windows and Obsidian.

**Comment by viduycheung** [comment] 2023-09-12 06:22
I tried this on Windows and the plugin can’t get the oauth token due to the Electron API. I’m planning on creating a new login process for Windows users. However, it might take some time. I’ll notify you once it’s launched.

**Comment by kmaustral** [comment] 2023-09-12 06:24
Good luck!

**Comment by neuromaancer** [comment] 2023-09-12 12:24
The same issue on macOS, blank authorization page. 
![image](https://github.com/viduycheung/ticktick-obsidian/assets/28112871/0c960411-f58c-42b7-b634-1d1b45c90c4b)

**Comment by viduycheung** [comment] 2023-09-13 10:02
I’ve updated the login method in version 1.0.1, please give it a try.

**Comment by kmaustral** [comment] 2023-09-13 12:06
Thanks. That works now. So at the moment it just allows you to create a task in TickTick. I presume there will be other commands eventually.

**Comment by viduycheung** [comment] 2023-09-14 01:40
> Thanks. That works now. So at the moment it just allows you to create a task in TickTick. I presume there will be other commands eventually.

Great, I'll close this issue. 
If you have any idea about the new command please create another issue.

**Closed as completed by viduycheung** 2023-09-14 01:40 UTC
